project:
  type: website
  output-dir: docs
  resources: 
    - CNAME

website:
  title: "💻🧰📊🥳"
  site-url: https://www.rdataviz.com/
  description: "HCS 7100: Data Visualization in R"
  favicon: img/code-slash.png
  back-to-top-navigation: true
  # google-analytics: "UA-XXXXXXXX"
  # license: "CC BY-NC"
  # copyright: 
  #   holder: "Jessica Cooperstone""
  #   year: 2023
  # search
  search:
    location: navbar
    type: overlay

  # options
  # reader-mode: false
  # repo-url: 
  # repo-actions: [edit, issue]
  # repo-branch: main
  # repo-subdir: docs

  # footer
  page-footer:
    border: true
    left: "Created with RStudio and [Quarto](https://quarto.org/) <br> © Jessica Cooperstone, 2024, License: [CC BY-NC 4.0](https://creativecommons.org/licenses/by-nc/4.0/) <br> [Want to make a website like this one?](https://osu-codeclub.github.io/#category=website)"
    right:
      - icon: github
        href: https://github.com/jcooperstone/rdataviz

  # nav
  navbar:
    logo: favicon.png
    tools:
      - icon: github
        href: https://github.com/jcooperstone/rdataviz
    left:
      # - sidebar:home
      - sidebar:syllabus
      - sidebar:modules
      - sidebar:recitations
      - sidebar:assignments
      - sidebar:solutions
    
    # right:
    #   - posts.qmd
    #   - release_notes.md
    #   - sidebar:contribute

  sidebar:
    # - id: home
    #   title: "Home"
      
    - id: syllabus
      title: "Syllabus"
      contents:
       - href: syllabus/syllabus.qmd
         text: Syllabus

    - id: modules
      title: "Course content"
      style: "docked"
      collapse-level: 2
      contents:
        - section: Module 1 - Principles
          contents:
            - href: modules/module1/01_principles/01_principles.qmd
              text: Week 1 - Principles
            - href: modules/module1/02_good-and-bad/02_goodbad.qmd
              text: Week 2 - Good and bad visualizations

        - section: Module 2 - Coding fundamentals
          contents:
            - href: modules/module2/03_rmarkdown/03_Rmd.qmd
              text: Week 3 - R Markdown
            - href: modules/module2/04_wrangling/04_wrangling.qmd
              text: Week 4 - Wrangling
            - href: modules/module2/05_ggplot101/05_ggplot101.qmd
              text: Week 5 - ggplot101
            - href: modules/module2/06_ggplot102/06_ggplot102.qmd
              text: Week 6 - ggplot102
        
        - section: Module 3 - Data exploration
          contents:
            - href: modules/module3/07_distributions/07_distributions.qmd
              text: Week 7 - Data distributions
            - href: modules/module3/08_correlations/08_correlations.qmd
              text: Week 8 - Correlations
            - href: modules/module3/09_add-stats/09_add-stats.qmd
              text: Week 9 - Adding statistics
            
        - section: Module 4 - Putting it together
          contents:
            - href: modules/module4/10_pca/10_pca.qmd
              text: Week 10 - Principal components analysis
            - href: modules/module4/11_manhattan/11_manhattan.qmd
              text: Week 11 - Manhattan plots
            - href: modules/module4/12_interactive-plots/12_interactive-plots.qmd
              text: Week 12 - Interactive plots
            - href: modules/module4/13_leftovers/13_leftovers.qmd
              text: Week 13 - Leftovers

    - id: recitations
      title: "Recitations"
      style: "docked"
      collapse-level: 2
      contents:
        - section: Module 2 - Coding fundamentals
          contents:
            - href: modules/module2/03_rmarkdown/03_Rmd_recitation.qmd
              text: Week 3 - R Markdown
            - href: modules/module2/04_wrangling/04_wrangling_recitation.qmd
              text: Week 4 - Wrangling
            - href: modules/module2/05_ggplot101/05_ggplot101_recitation.qmd
              text: Week 5 - ggplot101
            - href: modules/module2/06_ggplot102/06_ggplot102_recitation.qmd
              text: Week 6 - ggplot102
        
        - section: Module 3 - Data exploration
          contents:
            - href: modules/module3/07_distributions/07_distributions_recitation.qmd
              text: Week 7 - Data distributions
            - href: modules/module3/08_correlations/08_correlations_recitation.qmd
              text: Week 8 - Correlations
            - href: modules/module3/09_add-stats/09_add-stats_recitation.qmd
              text: Week 9 - Adding statistics
            
        - section: Module 4 - Putting it together
          contents:
            - href: modules/module4/10_pca/10_pca_recitation.qmd
              text: Week 10 - Principal components analysis
            - href: modules/module4/11_manhattan/11_manhattan_recitation.qmd
              text: Week 11 - Manhattan plots
            - href: modules/module4/12_interactive-plots/12_interactive-plots_recitation.qmd
              text: Week 12 - Interactive plots
            - href: modules/module4/13_leftovers/13_leftovers_recitation.qmd
              text: Week 13 - Leftovers
            
    - id: assignments
      title: "Assignments"
      style: "docked"
      collapse-level: 2
      contents:
        - section: Module assignments
          contents:
            - href: assignments/modules/module1/module_1_assignment.qmd
              text: Module 1
            - href: assignments/modules/module2/module_2_assignment.qmd
              text: Module 2
            - href: assignments/modules/module3/module_3_assignment.qmd
              text: Module 3
            - href: assignments/modules/module4/module_4_assignment.qmd
              text: Module 4              
              
        - section: Reflections
          contents:
            - href: assignments/reflections.qmd
              text: Reflection instructions
              
        - section: Capstone assignment
          contents:
            - href: assignments/capstone.qmd
              text: Capstone instructions

    - id: solutions
      title: "Solutions"
      style: "docked"
      collapse-level: 2
      contents:
        - section: Module assignment solutions
          contents:
            # - href: assignments/modules/module2/module_2_solutions.qmd
            #   text: Module 2 solutions
            # - href: assignments/modules/module3/module_3_solutions.qmd
            #   text: Module 3 solutions
            # - href: assignments/modules/module4/module_4_solutions.qmd
            #   text: Module 4 solutions

        - section: Recitation solutions
          contents:
            - href: https://github.com/jcooperstone/rdataviz/raw/main/rmds/03_Rmd_recitation_solutions.Rmd
              text: Week 3 - R Markdown solutions
            # - href: modules/module2/04_wrangling/04_wrangling_recitation_solutions.qmd
            #   text: Week 4 - Wrangling solutions
            # - href: modules/module2/05_ggplot101/05_ggplot101_recitation_solutions.qmd
            #   text: Week 5 - ggplot101 solutions 
            # - href: modules/module2/06_ggplot102/06_ggplot102_recitation_solutions.qmd
            #   text: Week 6 - ggplot102 solutions
            # - href: modules/module3/07_distributions/07_distributions_recitation_solutions.qmd
            #   text: Week 7 - Data distributions solutions
            # - href: modules/module3/08_correlations/08_correlations_recitation_solutions.qmd
            #   text: Week 8 - Correlations solutions
            # - href: modules/module3/09_add-stats/09_add-stats_recitation_solutions.qmd
            #   text: Week 9 - Adding statistics solutions
            # - href: modules/module4/10_pca/10_pca_recitation_solutions.qmd
            #   text: Week 10 - Principal components analysis solutions
            # - href: modules/module4/11_manhattan/11_manhattan_recitation_solutions.qmd
            #   text: Week 11 - Manhattan plots solutions
            # - href: modules/module4/12_interactive-plots/12_interactive-plots_recitation_solutions.qmd
            #   text: Week 12 - Interactive plots solutions
            # - href: modules/module4/13_leftovers/13_leftovers_recitation_solutions.qmd
            #   text: Week 13 - Leftovers solutions
      
format:
  html:
    theme:
      light: flatly
      dark: darkly


resources:
  - CNAME
