---
title: "Reflections"
---

## Reflections 
After each week, you will write a 1 paragraph reflection on the material that was presented in class. This can include your thoughts on how you will use these lessons in your own research and data visualizations, ways in which you have investigated this topic (or expect to) on your own, or what else you’d like to learn in this area. The purpose of this assignment is not to be burdensome, but to keep you engaged in the course material, and providing feedback to me on what parts you’ve found useful, what you’ve struggled with, and what you’d like to see more of in the future.

There will be 10 class reflections (you can select which classes you want to reflect upon).

**Due Date:** Reflections are due 1 week after each class. For example, if class is on Tuesday August 20, the reflection for that class is due on Tuesday August 28 by 11:59pm.

### Late assignments

I expect you will turn assignments in on time. Late assignments are not accepted. If there are extenuating circumstances that prevent you from turning in an assignment on time, please connect with me as soon as possible after such a situation arises for discussion about a possible deadline extension. 